#!/usr/bin/env python3
"""Write THRESHOLD_PROVENANCE.md from the code.

The file is cited from eleven places - the CLI's --provenance output, the footer
of every HTML report, the README, USAGE - and for a long time it did not exist,
so all eleven pointed at nothing. A reader who went looking for the sourcing
behind a FAIL found a dead reference, which is the opposite of what the citation
was for.

Generating it means it cannot drift from the values that actually grade a scan.
`tests/test_provenance_doc.py` fails if the checked-in file is stale.

    python tools/gen_provenance.py            # rewrite the file
    python tools/gen_provenance.py --check    # exit 1 if it is out of date
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from osipy_qc.core.config import (  # noqa: E402
    ORGANS, POPULATIONS, THRESHOLD_PROVENANCE, Provenance, QCConfig, for_population)

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THRESHOLD_PROVENANCE.md"

_TIER = {
    Provenance.PUBLISHED: (
        "📄 PUBLISHED",
        "A peer-reviewed paper states this number, for this purpose. These are the "
        "only thresholds that may decide a FAIL on their own."),
    Provenance.IMPLEMENTATION: (
        "💻 IMPLEMENTATION",
        "A reference implementation uses this value - code, not a paper. Reproducible "
        "and traceable, but never peer-reviewed as a quality cut-off."),
    Provenance.UNCALIBRATED: (
        "🔧 UNCALIBRATED",
        "Our engineering default. Not fitted to anything. A FAIL decided by one of "
        "these is marked *provisional* and `--no-strict` demotes it to a WARN."),
}


def _rows(level: Provenance):
    cfg = QCConfig()
    for name, (lvl, cite, note) in sorted(THRESHOLD_PROVENANCE.items()):
        if lvl is not level:
            continue
        val = getattr(cfg, name, None)
        yield name, ("—" if val is None else f"{val:g}" if isinstance(val, (int, float))
                     else str(val)), cite, note


def build() -> str:
    cfg = QCConfig()
    counts = {lvl: sum(1 for _n, (l, _c, _t) in THRESHOLD_PROVENANCE.items() if l is lvl)
              for lvl in Provenance}
    untagged = sorted(
        f for f in vars(cfg)
        if isinstance(getattr(cfg, f), (int, float)) and not isinstance(getattr(cfg, f), bool)
        and f not in THRESHOLD_PROVENANCE)

    L: list[str] = []
    add = L.append
    add("<!-- GENERATED by tools/gen_provenance.py - do not edit by hand. -->")
    add("<!-- Run `python tools/gen_provenance.py` after changing a threshold. -->")
    add("")
    add("# Where every PASS / FAIL number came from")
    add("")
    add("Most of this field has no published quality cut-offs. ASLPrep, ExploreASL, MRIQC")
    add("and fMRIPrep all report QC metrics and ship **zero verdict logic**. The QEI")
    add("cut-off (~0.5, Dolui 2024) is close to the only threshold in the ASL QC corpus")
    add("with a real published derivation.")
    add("")
    add("So rather than dress guesses up as evidence, every threshold below is tagged with")
    add("where it actually came from. If it cannot be cited, that is stated here rather")
    add("than hidden in a docstring.")
    add("")
    add(f"| tier | count | may decide a FAIL alone? |")
    add("|---|---:|---|")
    add(f"| 📄 published | {counts[Provenance.PUBLISHED]} | yes |")
    add(f"| 💻 implementation | {counts[Provenance.IMPLEMENTATION]} | yes, and it is recorded |")
    add(f"| 🔧 uncalibrated | {counts[Provenance.UNCALIBRATED]} | only as a *provisional* FAIL, "
        "which `--no-strict` demotes |")
    add("")
    add("> **What `provisional` means.** A FAIL decided by an uncalibrated cut-off is")
    add("> flagged in the report and demoted to a WARN by `--no-strict`. On a deliberately")
    add("> broken scan that is four failures against two: `1.qei` and `3.2.gm_wm_ratio`")
    add("> survive because a paper stands behind them; `3.1.cbf_level` and `3.3.negative_gm`")
    add("> do not. An uncalibrated number *can* reach a FAIL — it cannot do so silently.")
    add("")

    for level in (Provenance.PUBLISHED, Provenance.IMPLEMENTATION, Provenance.UNCALIBRATED):
        title, blurb = _TIER[level]
        add(f"## {title}")
        add("")
        add(blurb)
        add("")
        add("| threshold | default | source | what the source actually says |")
        add("|---|---|---|---|")
        for name, val, cite, note in _rows(level):
            note = note.replace("|", "\\|").replace("\n", " ")
            cite = cite.replace("|", "\\|").replace("\n", " ")
            add(f"| `{name}` | `{val}` | {cite} | {note} |")
        add("")

    add("## Population profiles")
    add("")
    add("CBF norms move enormously with age, so a single band would condemn whole")
    add("cohorts. The shipped profiles and the fields that differ between them:")
    add("")
    pops = list(POPULATIONS)
    add("| field | " + " | ".join(f"`{p}`" for p in pops) + " |")
    add("|---|" + "---|" * len(pops))
    base = {p: for_population(p) for p in pops}
    for f in sorted(vars(base[pops[0]])):
        vals = [getattr(base[p], f, None) for p in pops]
        if len({repr(v) for v in vals}) > 1:
            add(f"| `{f}` | " + " | ".join(f"`{v:g}`" if isinstance(v, (int, float))
                                           and not isinstance(v, bool) else f"`{v}`"
                                           for v in vals) + " |")
    add("")

    add("## Organ profiles")
    add("")
    for organ, meta in ORGANS.items():
        add(f"**`{organ}`** — {meta['note']}")
        add("")

    if untagged:
        add("## Not yet tagged")
        add("")
        add("These numeric config fields carry no entry in the machine-readable table, so")
        add("`provenance_of()` reports them as uncalibrated by default. Listing them here")
        add("is the to-do, not a claim that they are calibrated.")
        add("")
        add("".join(f"`{f}` · " for f in untagged).rstrip(" ·"))
        add("")

    add("---")
    add("")
    add("Regenerate with `python tools/gen_provenance.py`, or dump the same table at the")
    add("terminal with `osipy-qc --provenance`.")
    add("")
    return "\n".join(L)


if __name__ == "__main__":
    text = build()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"{OUT.name} is out of date - run: python tools/gen_provenance.py")
            sys.exit(1)
        print(f"{OUT.name} is current")
    else:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")
